VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsEncounterItem"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Emphasis As Integer

Public Line As String
Public Items As Collection

Public Function GetCreatureList(Optional AddToCol As Collection) As Collection
    Set GetCreatureList = modEncounter.GetCreatureList(Me, AddToCol)
End Function
